@companies = [
"Lapp GmbH Germany",
"K+S KALI GmbH Kassel Area, Germany",
"EVVA Sicherheitstechnologie GmbH Austria",
"DEG Cologne Area, Germany",
"Flughafen MÃ¼nchen GmbH Munich, Bavaria, Germany",
"Otto (GmbH & Co KG) Hamburg Hoheluft-Ost, Hamburg, Germany",
"MÃ¼hlbauer AG Regensburg Area, Germany",
"TUEV NORD AG Cologne Area, Germany",
"Star Cooperation Herrenberg, Baden-WÃ¼rttemberg, Germany",
"DB Systel GmbH Frankfurt Am Main Area, Germany",
"bauMax AG Austria",
"TQ-Systems GmbH Seefeld, Bavaria, Germany",
"Bayer Business Services Berlin, Berlin, Germany",
"Finanz Informatik GmbH & Co KG Hannover Area, Germany",
"Prinovis Ltd. & Co. KG NÃ¼rnberg Area, Germany",
"Peek&Cloppenburg KG Hamburg Hamburg Area, Germany",
"Stockmeier Group Dortmund Area, Germany",
"ADAC Munich Area, Germany",
"Autostadt GmbH Braunschweig Area, Germany",
"CACEIS Munich Area, Germany",
"GebrÃ¼der Weiss Gesellschaft m.b.H. Austria area",
"DÃœRKOP Automobile Kassel Area, Germany",
"FRÃ–BEL Bildung und Erziehung gemeinnÃ¼tzige GmbH Berlin Area, Germany",
"QVC Deutschland Inc. & Co. KG Germany",
"Lenzing AG Austria area",
"DS Smith Packaging Deutschland Stiftung & Co. KG Hanau, Hessen, Germany",
"Fortbildungsakademie der Wirtschaft (FAW) gGmbH Leipzig Area, Germany",
"ERGO Direkt Versicherungen NÃ¼rnberg Area, Germany",
"AOK Rheinland/Hamburg Cologne Area, Germany",
"Stieglbrauerei zu Salzburg GmbH Austria area",
"tesa Hamburg Area, Germany",
"Silvretta Montafon GmbH St. Gallenkirch, Vorarlberg, Austria",
"Welthungerhilfe Bonn, North Rhine-Westphalia, Germany",
"Raiffeisen Landesbank OÃ– Austria area",
"Lidl Ã–sterreich Austria area",
"GebrÃ¼der Weiss Gesellschaft m.b.H. Austria area",
"Oberbank Austria",
"Frankfurt University of Applied Sciences Bonn, North Rhine-Westphalia, Germany",
"Pankl Racing Systems AG Austria",
"Deutsche Sporthochschule KÃ¶ln Cologne Area, Germany",
"Ethicon EMEA Hamburg Area, Germany",
"Metabowerke GmbH Stuttgart Area, Germany",
"ErzdiÃ¶zese Wien Austria",
"BAUHAUS AG Berlin Area, Germany",
"EOS Munich Area, Germany",
"Magistrat Linz Austria",
"GE Power Frankfurt Am Main Area, Germany",
"McCann Worldgroup Deutschland Frankfurt Am Main Area, Germany",
"NestlÃ© Nespresso DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"REWE DORTMUND Dortmund Area, Germany",
"Deloitte Deutschland Cologne Area, Germany",
"IMPERIAL Logistics International B.V. & Co. KG Duisburg, North Rhine-Westphalia, Germany",
"WÃ¼stenrot Gruppe Austria area",
"REWE Digital GmbH Cologne Area, Germany",
"Endava Bad Vilbel, Hessen, Germany",
"Manz AG Stuttgart Area, Germany",
"LVM Dortmund Area, Germany",
"Ã–AMTC Austria area",
"Wayfair Berlin Area, Germany",
"A.T. Kearney Munich, Bavaria, Germany",
"AMS (Arbeitsmarktservice) Austria area",
"Weleda AG Stuttgart Area, Germany",
"Gruner + Jahr GmbH & Co KG Hamburg Area, Germany",
"Bardusch GmbH & Co. KG Ettlingen, Baden-WÃ¼rttemberg, Germany",
"Bilfinger Chemserv GmbH Austria",
"Nova Biomedical NÃ¼rnberg Area, Germany",
"TelefÃ³nica Germany Munich, Bavaria, Germany",
"Rundfunk Berlin-Brandenburg Berlin Area, Germany",
"WÃ¼stenrot Austria area",
"Frauenthal Service AG Vienna, Vienna, Austria",
"Zurich Gruppe Deutschland Cologne Area, Germany",
"HABAU Hoch- und Tiefbaugesellschaft m.b.H Austria",
"Silhouette International Austria",
"TRUMPF GmbH + Co. KG Stuttgart Area, Germany",
"Witt-Gruppe (a member of the otto group) Amberg, Bavaria, Germany",
"VELUX Hamburg Area, Germany",
"Bosch Service Solutions Kassel, Hessen, Germany",
"BAD GmbH KÃ¶ln, North Rhine-Westphalia, Germany",
"Axis Communications Hamburg Area, Germany",
"Globus ÄŒR, k.s. Leipzig, Saxony, Germany",
"Berufsbildungszentrum Augsburg der Lehmbaugruppe gGmbH BildungstrÃ¤ger Augsburg, Bavaria, Germany",
"Fronius International GmbH Austria area",
"Premium AEROTEC Augsburg, Bavaria, Germany",
"Otto (GmbH & Co KG) Hamburg Area, Germany",
"Papierfabrik August Koehler SE Achern, Baden-WÃ¼rttemberg, Germany",
"NetCologne KÃ¶ln, North Rhine-Westphalia, Germany",
"WILO SE Cologne Area, Germany",
"Infraserv HÃ¶chst Frankfurt Am Main Area, Germany",
"foodora Berlin, Berlin, Germany",
"GebrÃ¼der Weiss Ges.m.b.H. Kirchheim unter Teck, Baden-WÃ¼rttemberg, Germany",
"Ã–AMTC Vienna, Vienna, Austria",
"CHECK24 Vergleichsportal Munich, Bavaria, Germany",
"IFN Holding AG / Internorm International GmbH Austria",
"BAUHAUS Deutschland Heidelberg, Baden-WÃ¼rttemberg, Germany",
"APL Co. Germany Hamburg Area, Germany",
"Aloys F. Dornbracht GmbH & Co. KG Essen Area, Germany",
"Allianz Global Investors Munich Area, Germany",
"SportScheck Munich, Bavaria, Germany",
"FM Global Mannheim Area, Germany",
"Magistrat Linz Austria",
"Voith Digital Solutions Heidenheim an der Brenz, Baden-WÃ¼rttemberg, Germany",
"DekaBank Deutsche Girozentrale Bad Nauheim, Hessen, Germany",
"Synthomer plc. Bochum, North Rhine-Westphalia, Germany",
"STA Travel Frankfurt am Main, Hessen, Germany",
"Deloitte Deutschland Munich Area, Germany",
"European Central Bank Frankfurt Am Main Area, Germany",
"HARIBO Deutschland Bonn, North Rhine-Westphalia, Germany",
"ProjekttrÃ¤ger JÃ¼lich, Forschungszentrum JÃ¼lich GmbH Berlin Area, Germany",
"HSH Nordbank Kiel, Schleswig-Holstein, Germany",
"EWE AG Wardenburg, Lower Saxony, Germany",
"ARAMARK Holdings GmbH % Co. KG Dreieich, Hessen, Germany",
"Gealan Fenster-Systeme GmbH Marktredwitz, Bavaria, Germany",
"Maschinenfabrik Reinhausen Dieterskirchen, Bavaria, Germany",
"Goldbeck Group Bielefeld, North Rhine-Westphalia, Germany",
"Graz University of Technology Austria area",
"Vetter Pharma-Fertigung GmbH & Co. KG Ravensburg, Baden-WÃ¼rttemberg, Germany",
"ADAC Munich, Bavaria, Germany",
"HanseMerkur Versicherungsgruppe Hamburg Area, Germany",
"WBS TRAINING AG Potsdam, Brandenburg, Germany",
"Cyberport GmbH Ratingen, North Rhine-Westphalia, Germany",
"AOK Rheinland/Hamburg Kreisfreie Stadt Aachen Area, Germany",
"freenet AG Hamburg Area, Germany",
"Deutsche Windtechnik AG OsnabrÃ¼ck, Lower Saxony, Germany",
"ERGO Direkt Versicherungen NÃ¼rnberg Area, Germany",
"LVM Versicherung MÃ¼nster Dortmund Area, Germany",
"KBA (Koenig & Bauer Group) WÃ¼rzburg, Bavaria, Germany",
"WÃ¼rth Handelsges.m.b.H. Austria",
"Berlin Hyp AG Berlin, Berlin, Germany",
"Malteser Rhein-Ruhr gGmbH Essen, North Rhine-Westphalia, Germany",
"MTU Aero Engines Munich, Bavaria, Germany",
"Witt-Gruppe Germany",
"Zentis Bonn, North Rhine-Westphalia, Germany",
"Aareon AG Mainz, Rhineland-Palatinate, Germany",
"Leineweber GmbH & Co. KG Bad Salzuflen, North Rhine-Westphalia, Germany",
"AMS (Arbeitsmarktservice) Austria",
"Hekatron Sulzburg, Baden-WÃ¼rttemberg, Germany",
"MEAG Munich Area, Germany",
"GebrÃ¼der Weiss Gesellschaft m.b.H. Austria area",
"University of Applied Sciences Munich Munich Area, Germany",
"Technische Hochschule Mittelhessen GieÃŸen, Hessen, Germany",
"Allianz Asset Management AG Munich Area, Germany",
"WeidmÃ¼ller Deutschland Bielefeld Area, Germany",
"o2 (Germany) GmbH & Co. OHG Munich Area, Germany",
"WÃ¼stenrot & WÃ¼rttembergische Stuttgart Area, Germany",
"Bausparkasse SchwÃ¤bisch Hall AG Stuttgart Area, Germany",
"MDM MÃ¼nzhandelsgesellschaft mbH & Co. KG Deutsche MÃ¼nze Braunschweig, Lower Saxony, Germany",
"ADAC Munich, Bavaria, Germany",
"UPC Austria & Switzerland Vienna, Vienna, Austria",
"Hitachi Vantara Cologne Area, Germany",
"EOS Munich Area, Germany",
"Hogan Lovells Munich Area, Germany",
"Linklaters Germany",
"VTG AG Hamburg, Hamburg, Germany",
"DuMont Mediengruppe GmbH & Co. KG KÃ¶ln, North Rhine-Westphalia, Germany",
"AUVA Vienna, Vienna, Austria",
"Gebr. Brasseler GmbH & Co. KG Bielefeld, North Rhine-Westphalia, Germany",
"UniCredit Bank Austria AG Vienna, Vienna, Austria",
"SÃ¼dpack Verpackungen GmbH & Co. KG Munich Area, Germany",
"Hamburg Port Authority AÃ¶R Hamburg Area, Germany",
"K&L Ruppert Stiftung & Co. Handels-KG Weilheim in OberBavaria, Bavaria, Germany",
"Union Investment MÃ¼hlheim, Hessen, Germany",
"ING-DiBa Stuttgart Area, Germany",
"WÃ¼rth Industrie Service GmbH & Co. KG Bamberg, Bavaria, Germany",
"QSC AG KÃ¶ln, North Rhine-Westphalia, Germany",
"Oesterreichische Nationalbank Austria",
"ZITEC Gruppe GmbH Plattling, Bavaria, Germany",
"Georg-August-UniversitÃ¤t GÃ¶ttingen GÃ¶ttingen, Lower Saxony, Germany",
"SICK Freiburg Area, Germany",
"Austrian Airlines Vienna, Vienna, Austria",
"Messe Frankfurt GmbH Frankfurt am Main, Hessen, Germany",
"Management Financial Group NÃ¼rnberg, Bavaria, Germany",
"Sanacorp Pharmahandel GmbH Munich Area, Germany",
"Hermes Fulfilment GmbH Hamburg Area, Germany",
"Koch, Neff & Volckmar GmbH Stuttgart Area, Germany",
"Interroll Holding GmbH Cologne Area, Germany",
"EDAG Production Solutions GmbH & Co. KG Kassel, Hessen, Germany",
"PERI WeiÃŸenhorn, Bavaria, Germany",
"IAV GmbH Berlin, Berlin, Germany",
"GETRAG FORD Transmissions Cologne Area, Germany",
"E.ON Business Services Berlin Friedrichshain, Berlin, Germany",
"OBERMEYER Munich Area, Germany",
"ESG GmbH Munich Area, Germany",
"Schreiner Group GmbH & Co. KG Munich Area, Germany",
"bfw - Unternehmen fÃ¼r Bildung SaarbrÃ¼cken Area, Germany",
"Forschungszentrum JÃ¼lich JÃ¼lich, North Rhine-Westphalia, Germany",
"EFMD Mannheim, Baden-WÃ¼rttemberg, Germany",
"N3 Engine Overhaul Services GmbH & Co KG Erfurt, Thuringia, Germany",
"KPMG Deutschland Berlin, Berlin, Germany",
"Meyer Werft GmbH & Co. KG Weener, Lower Saxony, Germany",
"Rudolf GmbH Geretsried, Bavaria, Germany",
"Wien Energie GmbH Vienna, Vienna, Austria",
"Wiener StÃ¤dtische Versicherung AG - Vienna Insurance Group Vienna, Vienna, Austria",
"Saint-Gobain Weber KÃ¶ln, North Rhine-Westphalia, Germany",
"AOK Hessen Rodgau, Hessen, Germany",
"bfz gGmbH, bbw gGmbH Augsburg Area, Germany",
"Dieffenbacher Kirchheim am Neckar, Baden-WÃ¼rttemberg, Germany",
"GEZE GmbH Stuttgart Area, Germany",
"HERVIS Sport- und Modegesellschaft mbH. Eben im Pongau, Salzburg, Austria",
"OcÃ©    A CANON COMPANY Cologne Area, Germany",
"Coca-Cola European Partner Deutschland GmbH Berlin, Berlin, Germany",
"Desigual Berlin, Berlin, Germany",
"HENSOLDT Erbach, Baden-WÃ¼rttemberg, Germany",
"Linklaters Frankfurt am Main, Hessen, Germany",
"AMEDES Medizinische Dienstleistungen GmbH Hamburg EimsbÃ¼ttel, Hamburg, Germany",
"Dr. Becker Unternehmensgruppe HÃ¶henkirchen-Siegertsbrunn, Bavaria, Germany",
"Heinrich Heine GmbH Stuttgart Area, Germany",
"KLS Martin Tuttlingen, Baden-WÃ¼rttemberg, Germany",
"THE KADEWE GROUP Berlin, Berlin, Germany",
"NÃœRNBERGER Versicherung NÃ¼rnberg Area, Germany",
"LogMeIn Karlsruhe, Baden-WÃ¼rttemberg, Germany",
"Otto Bock HealthCare GmbH Duderstadt, Lower Saxony, Germany",
"AGRAVIS Raiffeisen AG MÃ¼nster, North Rhine-Westphalia, Germany",
"IABG Ottobrunn, Bavaria, Germany",
"Bayer Business Services KÃ¶ln, North Rhine-Westphalia, Germany",
"EDEKA Aktiengesellschaft Germany",
"E.ON Business Services Berlin Area, Germany",
"trans-o-flex Weinheim, Baden-WÃ¼rttemberg, Germany",
"WestfÃ¤lische Wilhelms-UniversitÃ¤t MÃ¼nster Germany",
"Wall GmbH Berlin, Berlin, Germany",
"UniCredit Bank Austria AG Vienna, Vienna, Austria",
"ENGIE Deutschland (vormals Cofely Deutschland - GDF Suez) Essen, North Rhine-Westphalia, Germany",
"Ã–AMTC Austria",
"Outotec Frankfurt Am Main Area, Germany",
"BNP Paribas Personal Investors NÃ¼rnberg Area, Germany",
"TÃœV NORD GROUP Cologne Area, Germany",
"T-Systems Multimedia Solutions GmbH Dresden Area, Germany",
"Witzenmann Group Stuttgart Area, Germany",
"EVVA Sicherheitstechnologie GmbH Vienna, Vienna, Austria",
"WOLF GmbH Munich Area, Germany",
"MADSACK Mediengruppe Hannover, Lower Saxony, Germany",
"SÃ¼wag Energie AG Frankfurt am Main, Hessen, Germany",
"comdirect bank AG Karlsruhe, Baden-WÃ¼rttemberg, Germany",
"medi NÃ¼rnberg Area, Germany",
"DB Systel GmbH Frankfurt Am Main Area, Germany",
"ALBA Group plc & Co. KG Berlin Area, Germany",
"Sanacorp Pharmahandel GmbH Planegg, Bavaria, Germany",
"T-Systems Multimedia Solutions GmbH Dresden, Saxony, Germany",
"Obeta electro - Oskar BÃ¶ttcher GmbH & Co.KG Berlin, Berlin, Germany",
"Johannes Gutenberg-UniversitÃ¤t Mainz Germany",
"KPMG Deutschland Berlin Area, Germany",
"Putzmeister Holding GmbH Stuttgart Area, Germany",
"UPC Austria & Switzerland Vienna, Vienna, Austria",
"Primetals Technologies Austria",
"Baumax AG Austria",
"50Hertz Transmission GmbH Berlin Area, Germany",
"Postcon Deutschland Cologne Area, Germany",
"GebrÃ¼der Weiss Gesellschaft m.b.H. Wels, Upper Austria, Austria",
"ESG Elektroniksystem- und Logistik-GmbH TÃ¼rkheim, Bavaria, Germany",
"EagleBurgmann Germany GmbH & Co. KG Munich Area, Germany",
"VACUUMSCHMELZE Frankfurt Am Main Area, Germany",
"Bayer Business Services DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"ImmobilienScout24 Berlin, Berlin, Germany",
"WOLFF & MÃœLLER Holding Stuttgart Area, Germany",
"SQS Group KÃ¶ln, North Rhine-Westphalia, Germany",
"dfv Mediengruppe (Deutscher Fachverlag GmbH) Frankfurt Am Main Area, Germany",
"Organization for Security and Co-operation in Europe (OSCE) Austria area",
"Uniklinik RWTH Aachen Kreisfreie Stadt Aachen Area, Germany",
"Bundesinstitut fÃ¼r Risikobewertung Berlin Area, Germany",
"ITK Engineering GmbH Karlsruhe, Baden-WÃ¼rttemberg, Germany",
"AGRAVIS Raiffeisen AG MÃ¼nster, North Rhine-Westphalia, Germany",
"Forschungszentrum JÃ¼lich Cologne Area, Germany",
"FOM Hochschule Marl, North Rhine-Westphalia, Germany",
"Karlsruher Institut fÃ¼r Technologie (KIT) Karlsruhe, Baden-WÃ¼rttemberg, Germany",
"LEONHARD KURZ Stiftung & Co.KG NÃ¼rnberg Area, Germany",
"AGRAVIS Raiffeisen AG Bielefeld Area, Germany",
"ElringKlinger AG Heppenheim, Hessen, Germany",
"Motor Presse Stuttgart GmbH & Co. KG Stuttgart Area, Germany",
"OTTO FUCHS - KG - Halver, North Rhine-Westphalia, Germany",
"Woco Industrietechnik GmbH Frankfurt Am Main Area, Germany",
"Bayerischer Rundfunk Munich, Bavaria, Germany",
"Horsch Maschinen GmbH Schwandorf, Bavaria, Germany",
"Big Dutchman International GmbH Vechta, Lower Saxony, Germany",
"Union Investment Frankfurt Am Main Area, Germany",
"Schwarz Dienstleistung KG Cologne Area, Germany",
"E. Breuninger GmbH & Co. Stuttgart Area, Germany",
"DekaBank Deutsche Girozentrale Frankfurt Am Main Area, Germany",
"BAUR Versand Weismain, Bavaria, Germany",
"Fiducia & GAD IT AG Dortmund Area, Germany",
"VerkehrsbÃ¼ro Group Austria area",
"Coca-Cola European Partners Deutschland GmbH Berlin, Berlin, Germany",
"CHECK24 Vergleichsportal Munich, Bavaria, Germany",
"HorvÃ¡th & Partners Management Consultants Stuttgart Area, Germany",
"Red Hat Stuttgart Plieningen, Baden-WÃ¼rttemberg, Germany",
"Danube University Austria area",
"Hexion Inc. Cologne Area, Germany",
"Dipl.-Ing. H. Sitte GmbH & Co. KG Hamburg Niendorf, Hamburg, Germany",
"UPC Austria Services GmbH Austria area",
"WAREMA Renkhoff SE WÃ¼rzburg, Bavaria, Germany",
"Storck Berlin Area, Germany",
"MEGA eG Hamburg Area, Germany",
"Klinikum Stuttgart Stuttgart Area, Germany",
"Austro Control Austria area",
"Gruner + Jahr Hamburg Area, Germany",
"moovel Group Stuttgart, Baden-WÃ¼rttemberg, Germany",
"Arthrex Munich Area, Germany",
"BOS GmbH & CO. KG Stuttgart Area, Germany",
"Terma A/S Frankfurt Am Main Area, Germany",
"Storck Berlin Area, Germany",
"BAUR Versand (GmbH & Co KG) Kulmbach, Bavaria, Germany",
"Berentzen-Gruppe AG Frankfurt Am Main Area, Germany",
"STILL GmbH Berlin, Berlin, Germany",
"NEMERA Freiburg Area, Germany",
"UniCredit Bank Austria AG Austria",
"SICK AG Freiburg Area, Germany",
"Metabowerke GmbH Stuttgart Area, Germany",
"Uponor Bamberg, Bavaria, Germany",
"Hauni Maschinenbau GmbH Hamburg Bergedorf, Hamburg, Germany",
"HELUKABEL GmbH Hemmingen, Baden-WÃ¼rttemberg, Germany",
"Austrian Federal Economic Chamber Austria area",
"WÃ¼rth Industrie Service GmbH & Co. KG WÃ¼rzburg Area, Germany",
"Simon Hegele Gesellschaft fÃ¼r Logistik und Service mbH Karlsruhe Area, Germany",
"AUVA Austria area",
"SIG Combibloc Hamburg Area, Germany",
"Verlagsgruppe Handelsblatt DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"BEUMER Group GmbH & Co. KG Paderborn, North Rhine-Westphalia, Germany",
"E.ON Business Service GmbH Berlin Area, Germany",
"Bechtle AG Neckarsulm, Baden-WÃ¼rttemberg, Germany",
"Kramp NÃ¼rnberg Area, Germany",
"Bayer Business Services KÃ¶ln, North Rhine-Westphalia, Germany",
"TÃœV AUSTRIA Brunn am Gebirge, Lower Austria, Austria",
"Thomas Cook Group Airlines / Condor Flugdienst Frankfurt Am Main Area, Germany",
"Zumtobel Group Lustenau, Vorarlberg, Austria",
"CHECK24 Vergleichsportal Munich Area, Germany",
"Bauhaus-UniversitÃ¤t Weimar Weimar, Thuringia, Germany",
"Uni Konstanz Konstanz Area, Germany",
"DekaBank Deutsche Girozentrale Munich Area, Germany",
"Landesbetrieb StraÃŸenbau NRW Gelsenkirchen, North Rhine-Westphalia, Germany",
"United States Agency for International Development Frankfurt Am Main Area, Germany",
"Hoffmann Group Munich Area, Germany",
"Lenzing Group Austria area",
"csi Verwaltungs GmbH / csi entwicklungtechnik GmbH Stuttgart Area, Germany",
"Bolta Werke GmbH NÃ¼rnberg Area, Germany",
"Bayer Business Services KÃ¶ln, North Rhine-Westphalia, Germany",
"Dillinger/Saarstahl Haina, Hessen, Germany",
"Atradius Credit Insurance Germany",
"SWR Stuttgart Area, Germany",
"Hansgrohe Group Schiltach, Baden-WÃ¼rttemberg, Germany",
"ElectronicPartner Handel SE DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"CHECK24 Vergleichsportal Munich, Bavaria, Germany",
"Tirol Kliniken GmbH Austria area",
"CSM Bakery Solutions Bremen, Bremen, Germany",
"BAD GmbH Aachen, North Rhine-Westphalia, Germany",
"NÃœRNBERGER Versicherung Munich, Bavaria, Germany",
"DMK Deutsches Milchkontor GmbH Germany",
"DECATHLON Deutschland Plochingen, Baden-WÃ¼rttemberg, Germany",
"MEDION AG Cologne Area, Germany",
"West Pharmaceutical Services Cologne Area, Germany",
"SIG Combibloc Cologne Area, Germany",
"Eisai Frankfurt Am Main Area, Germany",
"BD Rowa Germany GmbH Andernach, Rhineland-Palatinate, Germany",
"RUTRONIK Electronics Worldwide Ispringen, Baden-WÃ¼rttemberg, Germany",
"ADAC Munich Area, Germany",
"Teleperformance Germany S. Ã  r. l. & Co. KG Dortmund Area, Germany",
"Ã–sterreichische Nationalbank Austria area",
"Unitymedia Cologne Area, Germany",
"EagleBurgmann Germany",
"Clifford Chance Frankfurt am Main, Hessen, Germany",
"Ottobock HealthCare Duderstadt, Lower Saxony, Germany",
"ARRI Munich Area, Germany",
"Freenet AG Hamburg Area, Germany",
"Voith Hydro Germany",
"ZDF Germany",
"Regionalmedien Austria AG Austria",
"IAV GmbH Berlin Area, Germany",
"Flughafen Wien - Vienna Airport Austria",
"KPMG Deutschland Berlin, Berlin, Germany",
" ",
"E.ON Business Services Berlin, Berlin, Germany",
"Montblanc Hamburg Stellingen, Hamburg, Germany",
"DO & CO Group Austria area",
"Rama Academy Bremen Area, Germany",
"KNAPP AG Austria area",
"OSCE Vienna, Vienna, Austria",
"OSCE Austria area",
"Kapsch Group Austria",
"Eberspaecher Climate Control Systems TÃ¼bingen, Baden-WÃ¼rttemberg, Germany",
"AmRest Munich, Bavaria, Germany",
"SAP Hybris Munich, Bavaria, Germany",
"Messe Berlin GmbH Berlin Area, Germany",
" ",
"Allianz Global Investors Frankfurt am Main, Hessen, Germany",
"DO & CO Aktiengesellschaft Austria area",
"Subway KÃ¶ln, North Rhine-Westphalia, Germany",
"NestlÃ© Nespresso Austria",
"HorvÃ¡th & Partners Management Consultants Germany",
"SWK STADTWERKE KREFELD AG Wesel, North Rhine-Westphalia, Germany",
"StrÃ¶er SE & Co. KGaA KÃ¶ln, North Rhine-Westphalia, Germany",
"MCI Management Center Innsbruck - The Entrepreneurial SchoolÂ® Austria",
"Hans Turck GmbH & Co. KG MÃ¼lheim an der Ruhr, North Rhine-Westphalia, Germany",
"Flughafen Wien - Vienna Airport Austria area",
"MPREIS Warenvertriebs GmbH Innsbruck, Tyrol, Austria",
"Motor Presse Stuttgart GmbH & Co. KG  Stuttgart Area, Germany",
"WÃ¼stenrot & WÃ¼rttembergische Stuttgart Area, Germany",
"Unternehmensgruppe Messe Berlin Berlin Area, Germany",
"Markas G.m.b.H Gablitz, Lower Austria, Austria",
"Palfinger AG Austria area",
"Deutsche Messe AG Hannover, Lower Saxony, Germany",
"KlÃ¶ckner Metals Europe (KME) DÃ¼sseldorf Area, Germany",
"BAUHAUS Deutschland Mannheim, Baden-WÃ¼rttemberg, Germany",
"Ensinger GmbH Stuttgart Area, Germany",
"Promod Deutschland  GmbH Cologne Area, Germany",
"Bayer Business Services Berlin Area, Germany",
"Eissmann Group Automotive Stuttgart Area, Germany",
"August Faller GmbH & Co. KG Germany",
"Philipps-UniversitÃ¤t Marburg Frankfurt Am Main Area, Germany",
"Swiss Life AG, Niederlassung fÃ¼r Deutschland Munich, Bavaria, Germany",
"SICK AG Freiburg Area, Germany",
"Airbus Helicopters, Inc. Munich Area, Germany",
"Zollner Elektronik AG Zandt, Bavaria, Germany",
"Lidl Ã–sterreich Wals-Siezenheim, Salzburg, Austria",
"Lekkerland AG & Co. KG Cologne Area, Germany",
"OSCE Austria",
"Cornelsen Verlag GmbH Berlin Area, Germany",
"INFORM GmbH - Optimization Software Aachen, North Rhine-Westphalia, Germany",
"Fraunhofer IIS NÃ¼rnberg Area, Germany",
"SQS Group KÃ¶ln, North Rhine-Westphalia, Germany",
"OBS Aan de Meule Gangelt, North Rhine-Westphalia, Germany",
"Elektrobit (EB) Erlangen, Bavaria, Germany",
"DuMont Mediengruppe GmbH & Co. KG KÃ¶ln, North Rhine-Westphalia, Germany",
"Aurubis AG Hamburg Area, Germany",
"GEZE GmbH Stuttgart Area, Germany",
"Interhyp AG Munich, Bavaria, Germany",
"IKB Deutsche Industriebank AG DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"Freshfields Bruckhaus Deringer Frankfurt Am Main Area, Germany",
"PERI Ulm Area, Germany",
"Ziehm Imaging NÃ¼rnberg, Bavaria, Germany",
"SchÃ¼co International KG HÃ¶velhof, North Rhine-Westphalia, Germany",
"The Berner Group Langenfeld, North Rhine-Westphalia, Germany",
"BNP Paribas Real Estate DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"Europcar Hamburg Area, Germany",
"HANS IM GLÃœCK German Burgergrill Mannheim Area, Germany",
"Allianz Global Corporate & Specialty (AGCS) Munich Area, Germany",
"ERBER Group (Erber AG) Austria area",
"IABG Munich Area, Germany",
"AVM GmbH Berlin Area, Germany",
"Otto Bock HealthCare GmbH GÃ¶ttingen, Lower Saxony, Germany",
"Vistaprint Berlin Area, Germany",
"Sony Music Entertainment Munich, Bavaria, Germany",
"A1 Telekom Austria AG Austria area",
"UDG United Digital Group DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"Cogent Communications Frankfurt Am Main Area, Germany",
"Bechtle AG Heilbronn, Baden-WÃ¼rttemberg, Germany",
"Gira Giersiepen GmbH & Co KG Cologne Area, Germany",
"AGRAVIS Raiffeisen AG MÃ¼nster, North Rhine-Westphalia, Germany",
"Alpen-Adria-UniversitÃ¤t Austria area",
"Bentley Motors Ltd Munich Area, Germany",
"KLX Aerospace Solutions Hamburg Area, Germany",
"Schwarz Dienstleistung KG Neckarsulm, Baden-WÃ¼rttemberg, Germany",
"Lidl Ã–sterreich GmbH Austria area",
"Prinovis Ltd. & Co. KG NÃ¼rnberg Area, Germany",
"Voith Hydro Holding GmbH & Co. KG Ulm Area, Germany",
"Roland Berger Munich, Bavaria, Germany",
"Boetronic GmbH Munich Area, Germany",
"Verlagsgruppe Handelsblatt Wuppertal, North Rhine-Westphalia, Germany",
"WÃ¼rth Elektronik Group Hannover, Lower Saxony, Germany",
"QSC AG Cologne Area, Germany",
"Zurich Gruppe Deutschland Bonn, North Rhine-Westphalia, Germany",
"Stemmann-Technik GmbH Duisburg, North Rhine-Westphalia, Germany",
"Kalle GmbH Wiesbaden, Hessen, Germany",
"CHG-MERIDIAN AG Ravensburg, Baden-WÃ¼rttemberg, Germany",
"Marquard & Bahls AG Hamburg Area, Germany",
"Cartier Munich, Bavaria, Germany",
"Hauni Maschinenbau AG Hamburg, Hamburg, Germany",
"KPMG Deutschland Frankfurt Am Main Area, Germany",
"Sixt GmbH & Co. Autovermietung KG Munich, Bavaria, Germany",
"zeb consulting MÃ¼nster, North Rhine-Westphalia, Germany",
"trivago Cologne Area, Germany",
"Allianz Global Investors Frankfurt Am Main Area, Germany",
"Kapsch AG Austria area",
"DuMont Mediengruppe GmbH & Co. KG KÃ¶ln, North Rhine-Westphalia, Germany",
"Kaiser+Kraft Europa GmbH, TAKKT AG Stuttgart, Baden-WÃ¼rttemberg, Germany",
"Hoffmann Group Munich Area, Germany",
"Leica Microsystems Frankfurt Am Main Area, Germany",
"GebrÃ¼der Weiss Austria area",
"ProSiebenSat.1 Media SE Munich Area, Germany",
"SICK AG Freiburg Area, Germany",
"Mainova AG Germany",
"Zumtobel Group Austria area",
"Ketchum DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"Austrian Airlines Austria area",
"OSCE Vienna, Vienna, Austria",
"Kurtz Ersa Kreuzwertheim, Bavaria, Germany",
"Verlagsgruppe Random House GmbH Munich Area, Germany",
"GroupM Germany GmbH Cologne Area, Germany",
"TelefÃ³nica Germany Munich Area, Germany",
"AXA KÃ¶ln, North Rhine-Westphalia, Germany",
"Ludwig-Maximilians UniversitÃ¤t MÃ¼nchen Munich, Bavaria, Germany",
"ENGEL AUSTRIA GmbH Austria",
"Schmidt + Clemens GmbH + Co. KG Cologne Area, Germany",
"Wieland-Werke AG Stuttgart Area, Germany",
"Currenta GmbH & Co. OHG Cologne Area, Germany",
"BMW Bank GmbH Munich, Bavaria, Germany",
"DMK Deutsches Milchkontor GmbH Bremen Area, Germany",
"Kulzer  Frankfurt am Main, Hessen, Germany",
"Swiss Life AG Munich, Bavaria, Germany",
"Deloitte Deutschland DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"UniCredit Bank Austria AG Austria",
"VerkehrsbÃ¼ro Group Austria area",
"Bitburger Braugruppe GmbH Bitburg, Rhineland-Palatinate, Germany",
"Zurich Gruppe Deutschland Cologne Area, Germany",
"KIT Karlsruher Institut fÃ¼r Technologie Ettlingen, Baden-WÃ¼rttemberg, Germany",
"Dalli Group Cologne Area, Germany",
"ResMed Germany Inc. Munich Area, Germany",
"Brainlab Munich Area, Germany",
"Strategy&, part of the PwC network Munich Area, Germany",
"Deloitte Deutschland DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"UniversitÃ¤t Siegen Frankfurt Am Main Area, Germany",
"Deloitte Ã–sterreich Austria area",
"Spencer Stuart Frankfurt am Main, Hessen, Germany",
"Telekom Austria Group Austria area",
"Lapp Group Stuttgart Area, Germany",
"TEVA Merckle Ulm, Baden-WÃ¼rttemberg, Germany",
"Hach / Danaher Corporation Cologne Area, Germany",
"A1 Telekom Austria AG Austria area",
"Freenet AG Hamburg Area, Germany",
"Bank fÃ¼r Tirol und Vorarlberg AG Austria area",
"Doka Austria area",
"NORMA Group Maintal, Hessen, Germany",
"HOERBIGER Austria",
"Herba Chemosan Apotheker-AG Vienna, Vienna, Austria",
"Peter DÃ¶hle Schiffahrts-KG Hamburg Area, Germany",
"SSI SchÃ¤fer Austria area",
"Testo SE & Co. KGaA Lenzkirch, Baden-WÃ¼rttemberg, Germany",
"Diebold Nixdorf Paderborn, North Rhine-Westphalia, Germany",
"Crytek Frankfurt Am Main Area, Germany",
"HERE Technologies Berlin, Berlin, Germany",
"bfz gGmbH Kempten (AllgÃ¤u) Area, Germany",
"Q595 Munich Area, Germany",
"Zumtobel Group Dornbirn, Vorarlberg, Austria",
"HANSA-FLEX AG Bremen Area, Germany",
"Lufthansa Aviation Training GmbH Munich Area, Germany",
"SchÃ¼co International KG Bielefeld, North Rhine-Westphalia, Germany",
"ESG GmbH Munich Area, Germany",
"UniCredit Bank Austria AG Austria",
"ista International GmbH Essen, North Rhine-Westphalia, Germany",
"Zoetis Berlin Area, Germany",
"Red Bull Wals-Siezenheim, Salzburg, Austria",
"McKinsey & Company Deutschland Hamburg, Hamburg, Germany",
"JAGGAER Vienna, Vienna, Austria",
"The World Bank Cologne Area, Germany",
"Haas Food Equipment GmbH Austria area",
"European Central Bank Frankfurt Am Main Area, Germany",
"Rosenberger Hochfrequenztechnik GmbH & Co. KG Fridolfing, Bavaria, Germany",
"AUVA Austria",
"Frauenthal Service AG (UnternehmensÃ¼bergang aus SHT Haustechnik GmbH) Austria area",
"Wayfair Berlin, Berlin, Germany",
"CMS Legal Services EEIG Frankfurt am Main, Hessen, Germany",
"Hilton Munich Area, Germany",
"Linklaters Frankfurt Am Main Area, Germany",
"Russmedia Hard, Vorarlberg, Austria",
"Lam Research Austria",
"Fronius International GmbH Austria area",
"Red Hat EMEA Munich Area, Germany",
"MHP â€“ A Porsche Company Ludwigsburg, Baden-WÃ¼rttemberg, Germany",
"DB Engineering & Consulting GmbH Berlin, Berlin, Germany",
"LÃ¼ck Gruppe GieÃŸen, Hessen, Germany",
"HelmholtzZentrum MÃ¼nchen Munich Area, Germany",
"thyssenkrupp Presta AG Austria",
"RÃ¶chling Engineering Plastics KG MÃ¼nster Area, Germany",
"Molkerei MEGGLE Wasserburg GmbH & Co. KG Munich Area, Germany",
"Porsche Inter Auto GmbH & Co KG Austria area",
"SchÃ¼co International KG Bielefeld, North Rhine-Westphalia, Germany",
"Allianz Insurance Vienna, Vienna, Austria",
"Flughafen Stuttgart GmbH Stuttgart Area, Germany",
"K - Mail Order GmbH & Co. KG Pforzheim, Baden-WÃ¼rttemberg, Germany",
"Falkensteiner Hotels & Residences KÃ¶ln, North Rhine-Westphalia, Germany",
"Engel & VÃ¶lkers Hamburg Area, Germany",
"HARIBO Deutschland Cologne Area, Germany",
"Fischer Sports Ried im Innkreis, Upper Austria, Austria",
"MTU Aero Engines Munich, Bavaria, Germany",
"PTC Munich Area, Germany",
"A.T. Kearney DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"MSD Sharp & Dohme GmbH Munich Area, Germany",
"Ivoclar Vivadent AG Hard, Vorarlberg, Austria",
"The KaDeWe Group GmbH Berlin Friedrichshain, Berlin, Germany",
"KPMG Deutschland Berlin, Berlin, Germany",
"Brainlab Munich Area, Germany",
"Bayer HealthCare Cologne Area, Germany",
"R+S solutions Holding AG Fulda, Hessen, Germany",
"HorvÃ¡th & Partners Management Consultants Germany",
"A.T. Kearney DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"Freshfields Bruckhaus Deringer Frankfurt Am Main Area, Germany",
"Covestro Deutschland AG Cologne Area, Germany",
"Hays Mannheim, Baden-WÃ¼rttemberg, Germany",
"Fill Austria",
"Amer Sports Corporation Munich, Bavaria, Germany",
"SICK AG Freiburg Area, Germany",
"McKinsey & Company Austria area",
"Koenig & Bauer AG WÃ¼rzburg Area, Germany",
"Biogen Munich, Bavaria, Germany",
"Allianz Global Investors Frankfurt Am Main Area, Germany",
"Red Hat EMEA Stuttgart Area, Germany",
"AT&S Leoben, Styria, Austria",
"Berufsgenossenschaft Handel und Warenlogistik (BGHW) Mannheim, Baden-WÃ¼rttemberg, Germany",
"Vitra HR Services GmbH Weil am Rhein, Baden-WÃ¼rttemberg, Germany",
"DekaBank Frankfurt Am Main Area, Germany",
"Hettich Group Bielefeld Area, Germany",
"Sage Frankfurt Am Main Area, Germany",
"Zumtobel Group Austria area",
"Otto Bock HealthCare GmbH Erfurt Area, Germany",
"IDEXX Ludwigsburg, Baden-WÃ¼rttemberg, Germany",
"Otto Bock HealthCare GmbH Erfurt Area, Germany",
"KUKA Robotics Augsburg, Bavaria, Germany",
"TFE Hotels Berlin, Berlin, Germany",
"KfW Bonn, North Rhine-Westphalia, Germany",
"AMEDES Medizinische Dienstleistungen GmbH Hamburg Area, Germany",
"Julius Blum GmbH Austria",
"Coca-Cola ErfrischungsgetrÃ¤nke AG Berlin Area, Germany",
"Carcoustics Cologne Area, Germany",
"Zurich Gruppe Deutschland Cologne Area, Germany",
"HÃ¤fele GmbH & Co KG Nagold, Baden-WÃ¼rttemberg, Germany",
"i.s.c. - information security consulting e.U. Vienna, Vienna, Austria",
"OSCE Austria area",
"UniCredit Academy Austria | UniCredit Bank Austria AG Austria",
"Johnson Controls Ratingen, North Rhine-Westphalia, Germany",
"OSCE Vienna, Vienna, Austria",
"Sky Deutschland Fernsehen GmbH & Co. KG Munich Area, Germany",
"innogy Netz & Infrastruktur Cologne Area, Germany",
"ING-DiBa Frankfurt Am Main Area, Germany",
"HARIBO Deutschland Wachtberg, North Rhine-Westphalia, Germany",
"Zurich Gruppe Deutschland Cologne Area, Germany",
"Zumtobel Group Austria",
"Allgeier Experts SE MÃ¼hlheim, Hessen, Germany",
"Gallup Berlin, Berlin, Germany",
"Opel Vauxhall Financial Berlin Area, Germany",
"Greenpeace in Central and Eastern Europe Austria area",
"Lufthansa Cargo AG Germany",
"DKB Berlin Area, Germany",
"ista International GmbH Cologne Area, Germany",
"BNP Paribas Real Estate Frankfurt am Main, Hessen, Germany",
"ING-DiBa Frankfurt Am Main Area, Germany",
"Wacom Europe GmbH Krefeld, North Rhine-Westphalia, Germany",
"Lekkerland Cologne Area, Germany",
"Taylor Wessing Germany Hamburg Area, Germany",
"Lekkerland AG & Co. KG Cologne Area, Germany",
"Vattenfall Hamburg Area, Germany",
"EDEKA Aktiengesellschaft Hamburg, Hamburg, Germany",
"LINKLATERS LLP Frankfurt am Main, Hessen, Germany",
"Westfleisch SCE mbH Telgte, North Rhine-Westphalia, Germany",
"SICK AG Freiburg Area, Germany",
"Montblanc Hamburg Area, Germany",
"Mainova AG Germany",
"ADAC Munich Area, Germany",
"BSN medical Hamburg EimsbÃ¼ttel, Hamburg, Germany",
"WashTec AG Stuttgart, Baden-WÃ¼rttemberg, Germany",
"Cornelsen Verlag GmbH Berlin Area, Germany",
"Deutsche Welle Cologne Area, Germany",
"Mayr-Melnhof Karton GmbH Vienna, Vienna, Austria",
"EY Forstern, Bavaria, Germany",
"Otto Bock HealthCare GmbH, Duderstadt Berlin Area, Germany",
"Progroup AG Frankfurt Am Main Area, Germany",
"HARTING Bremen Area, Germany",
"E.ON Business Services Berlin GmbH Berlin Area, Germany",
"A1 Telekom Austria AG Austria area",
"West Pharmaceutical Services Cologne Area, Germany",
"Wayfair Berlin Kreuzberg, Berlin, Germany",
"WÃ¼stenrot Gruppe Austria area",
"https://www.linkedin.com/pub/kopping-nikolina/4/a38/812 Head of Leadership Development, Learning & Employer Branding",
"Vitra Freiburg Area, Germany",
"GM Financial Berlin Area, Germany",
"STRATO AG Berlin, Berlin, Germany"
]
