@companies = [
"A1 Telekom Austria AG Austria area",
"Freenet AG Hamburg Area, Germany",
"Bank fÃ¼r Tirol und Vorarlberg AG Austria area",
"Doka Austria area",
"NORMA Group Maintal, Hessen, Germany",
"HOERBIGER Austria",
"Herba Chemosan Apotheker-AG Vienna, Vienna, Austria",
"Peter DÃ¶hle Schiffahrts-KG Hamburg Area, Germany",
"SSI SchÃ¤fer Austria area",
"Testo SE & Co. KGaA Lenzkirch, Baden-WÃ¼rttemberg, Germany",
"Diebold Nixdorf Paderborn, North Rhine-Westphalia, Germany",
"Crytek Frankfurt Am Main Area, Germany",
"HERE Technologies Berlin, Berlin, Germany",
"bfz gGmbH Kempten (AllgÃ¤u) Area, Germany",
"Q595 Munich Area, Germany",
"Zumtobel Group Dornbirn, Vorarlberg, Austria",
"HANSA-FLEX AG Bremen Area, Germany",
"Lufthansa Aviation Training GmbH Munich Area, Germany",
"SchÃ¼co International KG Bielefeld, North Rhine-Westphalia, Germany",
"ESG GmbH Munich Area, Germany",
"UniCredit Bank Austria AG Austria",
"ista International GmbH Essen, North Rhine-Westphalia, Germany",
"Zoetis Berlin Area, Germany",
"Red Bull Wals-Siezenheim, Salzburg, Austria",
"McKinsey & Company Deutschland Hamburg, Hamburg, Germany",
"JAGGAER Vienna, Vienna, Austria",
"The World Bank Cologne Area, Germany",
"Haas Food Equipment GmbH Austria area",
"European Central Bank Frankfurt Am Main Area, Germany",
"Rosenberger Hochfrequenztechnik GmbH & Co. KG Fridolfing, Bavaria, Germany",
"AUVA Austria",
"Frauenthal Service AG (UnternehmensÃ¼bergang aus SHT Haustechnik GmbH) Austria area",
"Wayfair Berlin, Berlin, Germany",
"CMS Legal Services EEIG Frankfurt am Main, Hessen, Germany",
"Hilton Munich Area, Germany",
"Linklaters Frankfurt Am Main Area, Germany",
"Russmedia Hard, Vorarlberg, Austria",
"Lam Research Austria",
"Fronius International GmbH Austria area",
"Red Hat EMEA Munich Area, Germany",
"MHP â€“ A Porsche Company Ludwigsburg, Baden-WÃ¼rttemberg, Germany",
"DB Engineering & Consulting GmbH Berlin, Berlin, Germany",
"LÃ¼ck Gruppe GieÃŸen, Hessen, Germany",
"HelmholtzZentrum MÃ¼nchen Munich Area, Germany",
"thyssenkrupp Presta AG Austria",
"RÃ¶chling Engineering Plastics KG MÃ¼nster Area, Germany",
"Molkerei MEGGLE Wasserburg GmbH & Co. KG Munich Area, Germany",
"Porsche Inter Auto GmbH & Co KG Austria area",
"SchÃ¼co International KG Bielefeld, North Rhine-Westphalia, Germany",
"Allianz Insurance Vienna, Vienna, Austria",
"Flughafen Stuttgart GmbH Stuttgart Area, Germany",
"K - Mail Order GmbH & Co. KG Pforzheim, Baden-WÃ¼rttemberg, Germany",
"Falkensteiner Hotels & Residences KÃ¶ln, North Rhine-Westphalia, Germany",
"Engel & VÃ¶lkers Hamburg Area, Germany",
"HARIBO Deutschland Cologne Area, Germany",
"Fischer Sports Ried im Innkreis, Upper Austria, Austria",
"MTU Aero Engines Munich, Bavaria, Germany",
"PTC Munich Area, Germany",
"A.T. Kearney DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"MSD Sharp & Dohme GmbH Munich Area, Germany",
"Ivoclar Vivadent AG Hard, Vorarlberg, Austria",
"The KaDeWe Group GmbH Berlin Friedrichshain, Berlin, Germany",
"KPMG Deutschland Berlin, Berlin, Germany",
"Brainlab Munich Area, Germany",
"Bayer HealthCare Cologne Area, Germany",
"R+S solutions Holding AG Fulda, Hessen, Germany",
"HorvÃ¡th & Partners Management Consultants Germany",
"A.T. Kearney DÃ¼sseldorf, North Rhine-Westphalia, Germany",
"Freshfields Bruckhaus Deringer Frankfurt Am Main Area, Germany",
"Covestro Deutschland AG Cologne Area, Germany",
"Hays Mannheim, Baden-WÃ¼rttemberg, Germany",
"Fill Austria",
"Amer Sports Corporation Munich, Bavaria, Germany",
"SICK AG Freiburg Area, Germany",
"McKinsey & Company Austria area",
"Koenig & Bauer AG WÃ¼rzburg Area, Germany",
"Biogen Munich, Bavaria, Germany",
"Allianz Global Investors Frankfurt Am Main Area, Germany",
"Red Hat EMEA Stuttgart Area, Germany",
"AT&S Leoben, Styria, Austria",
"Berufsgenossenschaft Handel und Warenlogistik (BGHW) Mannheim, Baden-WÃ¼rttemberg, Germany",
"Vitra HR Services GmbH Weil am Rhein, Baden-WÃ¼rttemberg, Germany",
"DekaBank Frankfurt Am Main Area, Germany",
"Hettich Group Bielefeld Area, Germany",
"Sage Frankfurt Am Main Area, Germany",
"Zumtobel Group Austria area",
"Otto Bock HealthCare GmbH Erfurt Area, Germany",
"IDEXX Ludwigsburg, Baden-WÃ¼rttemberg, Germany",
"Otto Bock HealthCare GmbH Erfurt Area, Germany",
"KUKA Robotics Augsburg, Bavaria, Germany",
"TFE Hotels Berlin, Berlin, Germany",
"KfW Bonn, North Rhine-Westphalia, Germany",
"AMEDES Medizinische Dienstleistungen GmbH Hamburg Area, Germany",
"Julius Blum GmbH Austria",
"Coca-Cola ErfrischungsgetrÃ¤nke AG Berlin Area, Germany",
"Carcoustics Cologne Area, Germany",
"Zurich Gruppe Deutschland Cologne Area, Germany",
"HÃ¤fele GmbH & Co KG Nagold, Baden-WÃ¼rttemberg, Germany",
"i.s.c. - information security consulting e.U. Vienna, Vienna, Austria",
"OSCE Austria area",
"UniCredit Academy Austria | UniCredit Bank Austria AG Austria",
"Johnson Controls Ratingen, North Rhine-Westphalia, Germany",
"OSCE Vienna, Vienna, Austria",
"Sky Deutschland Fernsehen GmbH & Co. KG Munich Area, Germany",
"innogy Netz & Infrastruktur Cologne Area, Germany",
"ING-DiBa Frankfurt Am Main Area, Germany",
"HARIBO Deutschland Wachtberg, North Rhine-Westphalia, Germany",
"Zurich Gruppe Deutschland Cologne Area, Germany",
"Zumtobel Group Austria",
"Allgeier Experts SE MÃ¼hlheim, Hessen, Germany",
"Gallup Berlin, Berlin, Germany",
"Opel Vauxhall Financial Berlin Area, Germany",
"Greenpeace in Central and Eastern Europe Austria area",
"Lufthansa Cargo AG Germany",
"DKB Berlin Area, Germany",
"ista International GmbH Cologne Area, Germany",
"BNP Paribas Real Estate Frankfurt am Main, Hessen, Germany",
"ING-DiBa Frankfurt Am Main Area, Germany",
"Wacom Europe GmbH Krefeld, North Rhine-Westphalia, Germany",
"Lekkerland Cologne Area, Germany",
"Taylor Wessing Germany Hamburg Area, Germany",
"Lekkerland AG & Co. KG Cologne Area, Germany",
"Vattenfall Hamburg Area, Germany",
"EDEKA Aktiengesellschaft Hamburg, Hamburg, Germany",
"LINKLATERS LLP Frankfurt am Main, Hessen, Germany",
"Westfleisch SCE mbH Telgte, North Rhine-Westphalia, Germany",
"SICK AG Freiburg Area, Germany",
"Montblanc Hamburg Area, Germany",
"Mainova AG Germany",
"ADAC Munich Area, Germany",
"BSN medical Hamburg EimsbÃ¼ttel, Hamburg, Germany",
"WashTec AG Stuttgart, Baden-WÃ¼rttemberg, Germany",
"Cornelsen Verlag GmbH Berlin Area, Germany",
"Deutsche Welle Cologne Area, Germany",
"Mayr-Melnhof Karton GmbH Vienna, Vienna, Austria",
"EY Forstern, Bavaria, Germany",
"Otto Bock HealthCare GmbH, Duderstadt Berlin Area, Germany",
"Progroup AG Frankfurt Am Main Area, Germany",
"HARTING Bremen Area, Germany",
"E.ON Business Services Berlin GmbH Berlin Area, Germany",
"A1 Telekom Austria AG Austria area",
"West Pharmaceutical Services Cologne Area, Germany",
"Wayfair Berlin Kreuzberg, Berlin, Germany",
"WÃ¼stenrot Gruppe Austria area",
"https://www.linkedin.com/pub/kopping-nikolina/4/a38/812 Head of Leadership Development, Learning & Employer Branding",
"Vitra Freiburg Area, Germany",
"GM Financial Berlin Area, Germany",
"STRATO AG Berlin, Berlin, Germany"
]
